name 'mwser-opt'
maintainer 'Ed Sakabu'
maintainer_email 'EdSakabu@ucla.edu'
license 'Apache 2.0'
description 'Installs/Configures mwser-opt'
long_description 'Installs/Configures mwser-opt'
version '0.2.50'

depends 'opt'
depends 'mysql'
depends 'ruby_rbenv'
depends 'ruby_build'
depends 'nodejs'
depends 'nginx'
depends 'mysql2_chef_gem'
depends 'database'
